### ISSUE TITLE
[BUG] "comment.split" is not a function

### ISSUE THREAD

**Issue by Goldziher** [bcherny/json-schema-to-typescript#267]
Hi there. First of all thanks for your efforts! I've been using this tool with much success and find it very effective. Second - I'm experiencing a repeated issue when I'm converting openapi schemas of type array, namely this:

```TypeError: comment.split is not a function
    at generateComment (/Users/naamanhirschfeld/workspace/polyrepo/yoda-api-specs/node_modules/json-schema-to-typescript/dist/src/generator.js:251:22)
    at generateStandaloneInterface (/Users/naamanhirschfeld/workspace/polyrepo/yoda-api-specs/node_modules/json-schema-to-typescript/dist/src/generator.js:268:37)
    at declareNamedInterfaces (/Users/naamanhirschfeld/workspace/polyrepo/yoda-api-specs/node_modules/json-schema-to-typescript/dist/src/generator.js:63:128)
    at generate (/Users/naamanhirschfeld/workspace/polyrepo/yoda-api-specs/node_modules/json-schema-to-typescript/dist/src/generator.js:13:9)
    at Object.<anonymous> (/Users/naamanhirschfeld/workspace/polyrepo/yoda-api-specs/node_modules/json-schema-to-typescript/dist/src/index.js:120:68)
    at step (/Users/naamanhirschfeld/workspace/polyrepo/yoda-api-specs/node_modules/json-schema-to-typescript/dist/src/index.js:56:23)
    at Object.next (/Users/naamanhirschfeld/workspace/polyrepo/yoda-api-specs/node_modules/json-schema-to-typescript/dist/src/index.js:37:53)
    at fulfilled (/Users/naamanhirschfeld/workspace/polyrepo/yoda-api-specs/node_modules/json-schema-to-typescript/dist/src/index.js:28:58)```

**Comment by Manu1400** [comment]
Can you share your schema ?

**Comment by bcherny** [comment]
Closing for inactivity. Feel free to re-open if you can paste/link a schema so we can repro.
