### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by david-wb** [bcherny/json-schema-to-typescript#468]
After running

```
yarn run -s json2ts './schemas/fhir.r3.schema.json' \
  --ignoreMinAndMaxItems \
  --unreachableDefinitions \
  > src/generated/fhir3.ts
```

I get the following error
```
[
  RangeError: Maximum call stack size exceeded
      at memoized (/fhir-converter/node_modules/lodash/lodash.js:10612:30)
      at /fhir-converter/node_modules/json-schema-to-typescript/dist/src/generator.js:260:81
      at Array.map (<anonymous>)
      at generateSetOperation (/fhir-converter/node_modules/json-schema-to-typescript/dist/src/generator.js:260:30)
      at generateRawType (/fhir-converter/node_modules/json-schema-to-typescript/dist/src/generator.js:168:20)
      at generateTypeUnmemoized (/fhir-converter/node_modules/json-schema-to-typescript/dist/src/generator.js:143:16)
      at memoized (/fhir-converter/node_modules/lodash/lodash.js:10620:27)
      at /fhir-converter/node_modules/json-schema-to-typescript/dist/src/generator.js:271:72
      at Array.map (<anonymous>)
      at generateInterface (/fhir-converter/node_modules/json-schema-to-typescript/dist/src/generator.js:269:14)
]
```

I cannot attach the schema file here but if you ask, I will send it to you.

**Comment by bcherny** [comment]
Does this still repro on the latest version? If so, please repoen this issue and paste the JSON-schema (ideally, a pared down minimal repro) on this issue.
