### ISSUE TITLE
Cannot run json2ts?

### ISSUE THREAD

**Issue by pyros2097** [bcherny/json-schema-to-typescript#79]
When I run the command `json2ts`
I get his error,
```
module.js:472
    throw err;
    ^

Error: Cannot find module 'cli-color'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/pyros2097/.nvm/versions/node/v7.6.0/lib/node_modules/json-schema-to-typescript/dist/src/generator.js:3:19)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10
```
My node version is,
```
node v7.6.0
npm v4.1.2
```

**Comment by bcherny** [comment]
Published 4.1.5. Thanks for the report!
